/**
 * Defines a API macro to export/import symbols on Windows
 *
 * License: Mozilla Public License Version 2.0 (https://www.mozilla.org/en-US/MPL/2.0/ OR See accompanying file LICENSE)
 * Authors:
 *  - Dan Printzell
 */
#pragma once

#ifdef _WIN32
#define HYDRA_EXPORT_MACRO __declspec(dllexport)
#define HYDRA_IMPORT_MACRO __declspec(dllimport)
#else
#define HYDRA_EXPORT_MACRO
#define HYDRA_IMPORT_MACRO
#endif

#define HYDRA_SET_NULLPTR_MACRO = nullptr

#ifdef HYDRA_BASE_EXPORTS
#define HYDRA_BASE_API HYDRA_EXPORT_MACRO
#define HYDRA_BASE_SET_NULLPTR HYDRA_SET_NULLPTR_MACRO
#else
#define HYDRA_BASE_API HYDRA_IMPORT_MACRO
#define HYDRA_BASE_SET_NULLPTR
#endif

#ifdef HYDRA_GRAPHICS_EXPORTS
#define HYDRA_GRAPHICS_API HYDRA_EXPORT_MACRO
#define HYDRA_GRAPHICS_SET_NULLPTR HYDRA_SET_NULLPTR_MACRO
#else
#define HYDRA_GRAPHICS_API HYDRA_IMPORT_MACRO
#define HYDRA_GRAPHICS_SET_NULLPTR
#endif

#ifdef HYDRA_NETWORK_EXPORTS
#define HYDRA_NETWORK_API HYDRA_EXPORT_MACRO
#define HYDRA_NETWORK_SET_NULLPTR HYDRA_SET_NULLPTR_MACRO
#else
#define HYDRA_NETWORK_API HYDRA_IMPORT_MACRO
#define HYDRA_NETWORK_SET_NULLPTR
#endif

#ifdef HYDRA_PHYSICS_EXPORTS
#define HYDRA_PHYSICS_API HYDRA_EXPORT_MACRO
#define HYDRA_PHYSICS_SET_NULLPTR HYDRA_SET_NULLPTR_MACRO
#else
#define HYDRA_PHYSICS_API HYDRA_IMPORT_MACRO
#define HYDRA_PHYSICS_SET_NULLPTR
#endif

#ifdef HYDRA_SOUND_EXPORTS
#define HYDRA_SOUND_API HYDRA_EXPORT_MACRO
#define HYDRA_SOUND_SET_NULLPTR HYDRA_SET_NULLPTR_MACRO
#else
#define HYDRA_SOUND_API HYDRA_IMPORT_MACRO
#define HYDRA_SOUND_SET_NULLPTR
#endif
